### ISSUE TITLE
Improve exponential_smoothing Module

### ISSUE THREAD

**Issue by odtuyzt** [odtuyzt/chrono-kit#52]
Improve the exponential smoothing module by;

* Improve initialization functions:
  *  Improve the performance of already implented initialization methods
  *  Implement new initializations methods

* Improve model performances:
  * Implement methods to possibly improve implemented models' performances
  * Implement a "fit score" to evaluate models' performances

* Implement any other improvement that is suitable

**Comment by hasanemirakin** [comment]
Started changing models to support multivariable cases and testing model performance
