### ISSUE TITLE
Implement Autocorrelation and Partial Autocorrelation Functions

### ISSUE THREAD

**Issue by odtuyzt** [odtuyzt/chrono-kit#53]
Implement the ACF and PACF functions and functionalities related to these. Here's a good stackexchange feed on this topic for getting started: https://stats.stackexchange.com/questions/129052/acf-and-pacf-formula.

* Implement the ACF and PACF functions. (Also implementing a differencing function may be necessary for this)

* Implement ACF and PACF plots for visualizing the relevant results of these functions

**Comment by muguryalcin** [comment]
Started implementing.

**Comment by muguryalcin** [comment]
Done.
We might need to implement different calculation methods for pacf later, but should be fine for now.
