### ISSUE TITLE
Implement Additional Time Series Decompositions

### ISSUE THREAD

**Issue by odtuyzt** [odtuyzt/chrono-kit#55]
Implement time series decomposition methods other than classical. Refer to [Chapter 6 of FPP](https://otexts.com/fpp2/decomposition.html).

* Implement the STL decomposition

* Implement SEATS, X11 etc.. after ARIMA models are implemented

**Comment by hasanemirakin** [comment]
Started to implement LOWESS, LOESS and STL

**Comment by hasanemirakin** [comment]
Implemented LOWESS, LOESS and STL and pushed to branch "hasan"

**Comment by hasanemirakin** [comment]
Started implementing MSTL

**Comment by zhouyongxiu** [comment]
Have you  implemented SEATS?

**Comment by hasanemirakin** [comment]
@zhouyongxiu We haven't implemented SEATS or X11 yet. It's my plan to implement these methods after fixing some issues with the package
