### ISSUE TITLE
Implement a Basic NARX Class

### ISSUE THREAD

**Issue by odtuyzt** [odtuyzt/chrono-kit#68]
Implement a basic NARX class that has 1 hidden layer and returns a single output. The full specifications are;

* Has two different inputs;
  * x(t) with size (batch, window, 1)
  * y(t) with size (batch, window, 1)
 
* Has one hidden layer with following calculations;
  * x_out = Wx*x(t)
  * y_out = Wy*y(t) + b
  * Returns out = tanh(x_out + y_out)

* Output layer that takes the out from hidden layer and returns model output with shape (batch, 1)

You can set the window, batch and number of nodes in the hidden layer however you want. Below is an image example;

![img](https://www.mathworks.com/help/examples/nnet/win64/TrainNARXNetworkAndPredictOnNewDataExample_02.png)

**Comment by odtuyzt** [comment]
@muguryalcin Can you open a pr into the v1.1.x branch?

**Comment by hasanemirakin** [comment]
@muguryalcin  has implemented the class in PR #79
