### ISSUE TITLE
Implement a Neural Network Architecture Generation Function

### ISSUE THREAD

**Issue by odtuyzt** [odtuyzt/chrono-kit#69]
Implement a function or a class so that a neural network is generated according to the user specified parameters.

User will provide, input shape, output shape, number of hidden layers, nodes, activations, dropouts etc...

The function/class is expected to return a pytorch model with the given architecture, no training etc... is needed

**Comment by hasanemirakin** [comment]
@muguryalcin has implemented some groundwork for this issue in PR #79

**Comment by odtuyzt** [comment]
Below NARX class implemented by @muguryalcin provides a good base for building a NARX architecture with user specified architecture, any improvements/ideas are welcome

https://github.com/odtuyzt/chrono-kit/blob/c735bdc5788a742d5e461ed70f9ee9ce814895d3/chronokit/narx/narx.py#L42-L55

**Comment by hasanemirakin** [comment]
@muguryalcin has implemented the architecture generator class. Closing this as completed
