### ISSUE TITLE
Python Linting

### ISSUE THREAD

**Issue by KananMahammadli** [odtuyzt/chrono-kit#75]
Add Black, Flake8-like support to the project for automatic linting of the files and ensuring PEP8 standards.  Better to have scripts to run black and flake8 so that every PR opened can be run locally. Add linting check to PRs; if black or flake8 fails, PR won't be merged.

Basic usage:
`python -m black --line-length=79 --target-version=py39 --verbose chronokit`
`python -m flake8 --verbose`

**Comment by odtuyzt** [comment]
Related branch was merged into v0.1.1x
