### ISSUE TITLE
Improvement of Exponential Smoothing methods

### ISSUE THREAD

**Issue by araslidogukan** [odtuyzt/chrono-kit#78]
- Need to increase the flexibility of the exponential smoothing methods. With some examples as the following:

1. Model selection requires at least 2 full seasons even when seasonality is set as _None_
2. Initialization method _heuristic_ requires 10 data to initialize, may be set to a changing value
3. When setting smoothing models explicitly (e.g., SES() ), smoothing constants required for that spesific model should be arguments rather than in **kwargs since changing those values for a model, seeing their defaults should be easier.

model_selection and initalization _mle_ should be checked. Seems to be not working properly.

**Comment by hasanemirakin** [comment]
* Haven't gotten to work on the model selection yet.
* Heuristic initialization requires a minimum of 10 observations. The level and trend components are initialized by running a linear regression on the first 10 observations. see [Exponential Smoothing by Hyndman et al.](https://link.springer.com/book/10.1007/978-3-540-71918-2) Chapter 2.6.1
* I am not sure about setting model parameter as default arguments. As normally they should be numerically estimated by a optimizer function which can be selected by "initialization_method" argument. Specifying set values for these parameters should be a rare case.
* Performance of the _mle_ initialization was improved. Also added minimizng _sse_ as initialization. Check [commit](https://github.com/odtuyzt/chrono-kit/commit/1485763d06a686518074641d7a7f9d60c56a72b8)

**Comment by hasanemirakin** [comment]
* Model selection was also improved. Check [commit](https://github.com/odtuyzt/chrono-kit/commit/fcd313e4d10d1993612d8c93fe5fda6e3fbe646e)
